// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyD5PZi5yMC7qRbkGsZmis74Xq-9UHFiupQ',
  //   appId: '1:169292998939:web:457643e69c412e042e4bbe',
  //   messagingSenderId: '169292998939',
  //   projectId: 'pjhousewebsite',
  //   authDomain: 'pjhousewebsite.firebaseapp.com',
  //   storageBucket: 'pjhousewebsite.appspot.com',
  //   measurementId: 'G-F19DR3D025',
  // );

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyD8C8NbcyFZVDj3Y0LQNPYyf5UBnZyak20",
      authDomain: "pjhouseweb.firebaseapp.com",
      projectId: "pjhouseweb",
      storageBucket: "pjhouseweb.appspot.com",
      messagingSenderId: "919212803186",
      appId: "1:919212803186:web:23d1c080ac4a8c6bc6eeeb",
      measurementId: "G-FSRDP6KH9Q"
  );
}
